spring:
  datasource:
    url: jdbc:mysql://localhost/authn?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin
  sql:
    init:
      mode: always
jwt:
  secret: 'q@7}Z]k7D9#>5M(B`Qu?AJ8'

server:
  port: 8090